---
- name: Install Docker on all servers
  hosts: all

  tasks:
    - name: Install EPEL
      import_role:
        name: geerlingguy.repo-epel             # EPEL is needed for pip role
    - name: Install setuptools
      yum:
        name: python-setuptools
        state: latest
    - name: Install pip and Docker compose SDK
      import_role:
        name: geerlingguy.pip                   # Pip is needed for Docker compose
      vars:
        pip_package: python-pip
        pip_install_packages:
          - name: docker-compose
            version: 1.13.0
    - name: Install pip3 and Docker SDK
      import_role:
        name: geerlingguy.pip                   # Pip3 is needed for Docker
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
            version: 5.0.0
          - name: six
    - name: Install Docker
      import_role:
        name: geerlingguy.docker

- name: Configure servers with Docker registry
  hosts:
    - frontend
    - backend
    - build
  tasks:
    - name: Enable insecure communication with Docker registry
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0664
      notify: 
        - Restart Docker
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
