---
- name: Install Docker on all servers
  hosts: all
  become: yes

  tasks:
    - name: Install EPEL
      import_role:
        name: geerlingguy.repo-epel           # EPEL is needed for pip role
    - name: Install pip and pip Docker
      import_role:
        name: geerlingguy.pip                 # Pip is needed for Docker
      vars:
        pip_package: python-pip
        pip_install_packages:
          - name: docker-py
    - name: Install setuptools
      yum:
        name: python-setuptools
        state: latest
    - name: Install Docker
      import_role:
        name: geerlingguy.docker

- name: Configure servers with Docker registry
  hosts:
    - frontend
    - backend
    - build
  tasks:
    - name: Enable insecure communication with Docker registry
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0664
      notify: 
        - Restart Docker
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted