---
- name: Build BE Docker image and push to Docker registry
  hosts: build
  force_handlers: yes
  tasks:
    - name: Git checkout
      git:
        repo: "ssh://git@{{ hostvars[groups['repository'][0]]['ansible_host'] }}:2222/git-server/repos/videosonik-backend.git"
        dest: "/home/{{ ansible_user }}/videosonik-backend"
        key_file: /home/{{ ansible_user }}/.ssh/build_server
        accept_hostkey: yes
        version: master
      notify: 
        - Clean workspace
    - name: Load Postgres configuration variables from encrypted file
      include_vars:
        file: vault/database-config.yml
    - name: Template application.properties
      template:
        src: application.properties.j2
        dest: "/home/{{ ansible_user }}/videosonik-backend/src/main/resources/application.properties"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: /home/{{ ansible_user }}/videosonik-backend
          pull: yes
        name: "{{ hostvars[groups['repository'][0]]['ansible_host'] }}:5000/videosonik-backend"
        tag: latest
        push: yes
        source: build
      vars:
        ansible_python_interpreter: /bin/python3
    - name: Remove Docker image
      docker_image:
        state: absent
        name: "{{ hostvars[groups['repository'][0]]['ansible_host'] }}:5000/videosonik-backend"
        tag: latest
      vars:
        ansible_python_interpreter: /bin/python3
  handlers:
    - name: Clean workspace
      file:
        path: /home/{{ ansible_user }}/videosonik-backend
        state: absent