---
- name: Build BE Docker image and push to Docker registry
  hosts: build
  force_handlers: yes
  tasks:
    - name: Load secret variables from encrypted file
      include_vars:
        file: vault/secret-config.yml
    - name: Clean workspace
      file:
        path: /home/{{ ansible_user }}/videosonik-backend
        state: absent
    - name: Git checkout
      git:
        repo: "{{ git_server_url }}/videosonik-backend.git"
        dest: "/home/{{ ansible_user }}/videosonik-backend"
        key_file: "{{ git_key_file }}"
        accept_hostkey: yes
        version: master
    - name: Template application.properties
      template:
        src: application.properties.j2
        dest: "/home/{{ ansible_user }}/videosonik-backend/src/main/resources/application.properties"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: /home/{{ ansible_user }}/videosonik-backend
          pull: yes
        name: "{{ docker_registry_url }}/videosonik-backend"
        tag: latest
        push: yes
        source: build
      vars:
        ansible_python_interpreter: /bin/python3
    - name: Remove Docker image
      docker_image:
        state: absent
        name: "{{ docker_registry_url }}/videosonik-backend"
        tag: latest
      vars:
        ansible_python_interpreter: /bin/python3
