---
- name: Configure build server with Git
  hosts: build
  tasks:
    - name: Install Git
      import_role:
        name: geerlingguy.git
      vars:
        git_install_from_source: true
        git_version: "2.30.0"
        git_install_from_source_force_update: true
    - name: Install pip3 and pip3 Docker
      import_role:
        name: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
    - name: Generate SSH key
      openssh_keypair:
        path: "{{ git_key_file }}"
        size: 2048
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Template SSH config
      template:
        src: config.j2
        dest: "/home/{{ ansible_user }}/.ssh/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
    - name: Fetch SSH key from build server
      fetch:
        src: "{{ git_key_file }}.pub"
        dest: buffer/build_server.pub
        flat: yes

- name: Set up SSH to remote Git server
  hosts: repository
  tasks:
    - name: Copy SSH key to Git server
      copy:
        src: buffer/build_server.pub
        dest: "{{ git_keys_folder }}/build_server.pub"
      notify:
        - Restart the Docker container of the Git server
    - name: Clean up Ansible master
      file:
        path: buffer/
        state: absent
      delegate_to: 127.0.0.1
  handlers:
    - name: Restart the Docker container of the Git server
      docker_container:
        name: git-server
        image: jkarlos/git-server-docker
        state: started
        restart: yes
        volumes:
          - "{{ git_keys_folder }}:/git-server/keys"
          - "{{ git_repos_folder }}:/git-server/repos"
        ports:
          - "2222:22"