---
- name: Deploy the Postgres database
  hosts: database
  tasks:
    - name: Create necessary folder for Docker volume
      file:
        path: "{{ postgres_folder }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0775
    - name: Load Postgres configuration variables from encrypted file
      include_vars:
        file: vault/secret-config.yml
    - name: Run Postgres in Docker container
      docker_container:
        name: postgres
        image: postgres:11
        state: started
        volumes:
          - "{{ postgres_folder }}:/var/lib/postgresql/data"
        ports:
          - "{{ database_port }}:5432"
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_pass }}"
          POSTGRES_DB: "{{ database_name }}"