---
- name: Install Docker on all servers
  hosts: all
  become: yes

  tasks:
    - name: Install setuptools
      yum:
        name: python-setuptools
        state: latest
    - name: Install EPEL
      import_role:
        name: geerlingguy.repo-epel           # EPEL is needed for pip role
    - name: Install pip and pip Docker
      import_role:
        name: geerlingguy.pip                 # Pip is needed for Docker
      vars:
        pip_package: python-pip
        pip_install_packages:
          - name: docker-py
    - name: Install Docker
      import_role:
        name: geerlingguy.docker
