---
- name: Build FE Docker image and push to Docker registry
  hosts: build
  force_handlers: yes
  tasks:
    - name: Clean workspace
      file:
        path: /home/{{ ansible_user }}/videosonik-frontend
        state: absent
    - name: Git checkout
      git:
        repo: "{{ git_server_url }}/videosonik-frontend.git"
        dest: "/home/{{ ansible_user }}/videosonik-frontend"
        key_file: "{{ git_key_file }}"
        accept_hostkey: yes
        version: master
    - name: Template backend configuration
      template:
        src: custom-axios.js.j2
        dest: "/home/{{ ansible_user }}/videosonik-frontend/src/axios/custom-axios.js"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644 
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: /home/{{ ansible_user }}/videosonik-frontend
          pull: yes
        name: "{{ docker_registry_url }}/videosonik-frontend"
        tag: latest
        push: yes
        source: build
      vars:
        ansible_python_interpreter: /bin/python3
    - name: Remove Docker image
      docker_image:
        state: absent
        name: "{{ docker_registry_url }}/videosonik-frontend"
        tag: latest
      vars:
        ansible_python_interpreter: /bin/python3
