---
- name: Generate SSH key on local machine for Git servers
  hosts: localhost
  become: no
  vars_prompt:
    - name: "ssh_key_name"
      prompt: "Enter the name of the SSH key for connecting to the Git server"
      private: no
  tasks:
    - name: Generate SSH key
      openssh_keypair:
        path: "/home/{{ ansible_user }}/.ssh/{{ ssh_key_name }}"
        size: 2048
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Template SSH config
      template:
        src: config.j2
        dest: "/home/{{ ansible_user }}/.ssh/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
    - name: Set SSH key name as host variable
      set_fact:
        local_public_key_location: "/home/{{ ansible_user }}/.ssh/{{ ssh_key_name }}.pub"

- name: Install Git server
  hosts: repository
  tasks:
    - name: Create necessary folders for Git server
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0775
      loop:
        - "{{ git_server_folder }}"
        - "{{ git_keys_folder }}"
        - "{{ git_repos_folder }}"
    - name: Set up public key
      copy:
        src: "{{ hostvars['localhost']['local_public_key_location'] }}"
        dest: "{{ git_keys_folder }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
    - name: Run Git server in a Docker container
      docker_container:
        name: git-server
        image: jkarlos/git-server-docker
        state: started
        restart: yes
        volumes:
        - "{{ git_keys_folder }}:/git-server/keys"
        - "{{ git_repos_folder }}:/git-server/repos"
        ports:
          - "2222:22"
      vars:
        ansible_python_interpreter: /bin/python3

- name: Install Docker registry
  hosts: repository
  tasks:
    - name: Create necessary folder for Docker registry
      file:
        path: "/home/{{ ansible_user }}/docker-registry"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0775
    - name: Run Docker registry in a container
      become: yes
      docker_container:
        name: docker-registry
        image: registry:2
        state: started
        restart: yes
        volumes:
          - "/home/{{ ansible_user }}/docker-registry:/var/lib/registry"
        ports:
          - "5000:5000"
      vars:
        ansible_python_interpreter: /bin/python3
