---
- name: Restart repository Docker containers
  hosts: repository
  tasks:
    - name: Restart the Docker container of the Git server
      docker_container:
        name: git-server
        image: jkarlos/git-server-docker
        state: started
        restart: yes
        volumes:
          - "{{ git_keys_folder }}:/git-server/keys"
          - "{{ git_repos_folder }}:/git-server/repos"
        ports:
          - "2222:22"
    - name: Restart the Docker container of the Docker registry
      become: yes
      docker_container:
        name: docker-registry
        image: registry:2
        state: started
        restart: yes
        volumes:
          - "/home/{{ ansible_user }}/docker-registry:/var/lib/registry"
        ports:
          - "5000:5000"